#pragma once
#include <lvgl.h>

// Lucide "lightbulb" (lucide.dev/icons/lightbulb), rasterised from the
// upstream SVG to a 26x26 LV_IMG_CF_ALPHA_8BIT bitmap.
//
// It's alpha-only, so it carries no colour of its own -- LVGL paints it
// with the object's `img_recolor` style. That lets the dial tint it exactly
// like the LV_SYMBOL_* text icons it sits alongside (see ui_dial.cpp's
// layoutRing), which a normal colour image couldn't do.
//
// Regenerated by scratchpad/gen_bulb.py if the source icon ever changes.
extern const lv_img_dsc_t iconLightbulb;
